actionLinkGroupTemplates:
    - type: ActionLinkGroupTemplate
      class: MetadataFilenameParser
      extension: actionLinkGroupTemplate
analyticSnapshots:
    - type: AnalyticSnapshot
      class: MetadataFilenameParser
      extension: snapshot
animationRules:
    - type: AnimationRule
      class: MetadataFilenameParser
      extension: animationRule
applications:
    - type: CustomApplication
      class: MetadataFilenameParser
      extension: app
appMenus:
    - type: AppMenu
      class: MetadataFilenameParser
      extension: appMenu
appointmentSchedulingPolicies:
    - type: AppointmentSchedulingPolicy
      class: MetadataFilenameParser
      extension: policy
approvalProcesses:
    - type: ApprovalProcess
      class: MetadataFilenameParser
      extension: approvalProcess
assignmentRules:
    - type: AssignmentRule
      class: MetadataFilenameParser
      extension: assignmentRules
aura:
    - type: AuraDefinitionBundle
      class: BundleParser
authproviders:
    - type: AuthProvider
      class: MetadataFilenameParser
      extension: authprovider
autoResponseRules:
    - type: AutoResponseRules
      class: MetadataFilenameParser
      extension: autoResponseRules
brandingSets:
    - type: BrandingSet
      class: MetadataFilenameParser
      extension: brandingSet
cachePartitions:
    - type: PlatformCachePartition
      class: MetadataFilenameParser
      extension: cachePartition
callCenters:
    - type: CallCenter
      class: MetadataFilenameParser
      extension: callCenter
campaignInfluenceModels:
    - type: CampaignInfluenceModel
      class: MetadataFilenameParser
      extension: campaignInfluenceModel
CaseSubjectParticles:
    - type: CaseSubjectParticle
      class: MetadataFilenameParser
      extension: CaseSubjectParticle
certs:
    - type: Certificate
      class: MetadataFilenameParser
      extension: crt
channelLayouts:
    - type: ChannelLayout
      class: MetadataFilenameParser
      extension: channelLayout
ChatterExtensions:
    - type: ChatterExtension
      class: MetadataFilenameParser
      extension: ChatterExtension
classes:
    - type: ApexClass
      class: MetadataFilenameParser
      extension: cls
cleanDataServices:
    - type: CleanDataService
      class: MetadataFilenameParser
      extension: cleanDataService
communities:
    - type: Community
      class: MetadataFilenameParser
      extension: community
communityTemplateDefinitions:
    - type: CommunityTemplateDefinition
      class: MetadataFilenameParser
      extension: communityTemplateDefinition
communityThemeDefinitions:
    - type: CommunityThemeDefinition
      class: MetadataFilenameParser
      extension: communityThemeDefinition
components:
    - type: ApexComponent
      class: MetadataFilenameParser
      extension: component
connectedApps:
    - type: ConnectedApp
      class: MetadataFilenameParser
      extension: connectedApp
contentassets:
    - type: ContentAsset
      class: MetadataFilenameParser
      extension: asset
corsWhitelistOrigins:
    - type: CorsWhitelistOrigin
      class: MetadataFilenameParser
      extension: corsWhitelistOrigin
cspTrustedSites:
    - type: CspTrustedSite
      class: MetadataFilenameParser
      extension: cspTrustedSite
customHelpMenuSections:
    - type: CustomHelpMenuSection
      class: MetadataFilenameParser
      extension: customHelpMenuSection
customMetadata:
    - type: CustomMetadata
      class: MetadataFilenameParser
      extension: md
customPermissions:
    - type: CustomPermission
      class: MetadataFilenameParser
      extension: customPermission
dashboards:
    - type: Dashboard
      class: MetadataFolderParser
datacategorygroups:
    - type: DataCategoryGroup
      class: MetadataFilenameParser
      extension: datacategorygroup
dataSources:
    - type: ExternalDataSource
      class: MetadataFilenameParser
      extension: dataSource
delegateGroups:
    - type: DelegateGroup
      class: MetadataFilenameParser
      extension: delegateGroup
documents:
    - type: Document
      class: DocumentParser
duplicateRules:
    - type: DuplicateRule
      class: MetadataFilenameParser
      extension: duplicateRule
eclair:
    - type: EclairGeoData
      class: MetadataFilenameParser
      extension: geodata
email:
    - type: EmailTemplate
      class: MetadataFolderParser
emailservices:
    - type: EmailServicesFunction
      class: MetadataFilenameParser
      extension: xml
EmbeddedServiceBranding:
    - type: EmbeddedServiceBranding
      class: MetadataFilenameParser
      extension: EmbeddedServiceBranding
EmbeddedServiceConfig:
    - type: EmbeddedServiceConfig
      class: MetadataFilenameParser
      extension: EmbeddedServiceConfig
EmbeddedServiceFlowConfig:
    - type: EmbeddedServiceFlowConfig
      class: MetadataFilenameParser
      extension: EmbeddedServiceFlowConfig
EmbeddedServiceLiveAgent:
    - type: EmbeddedServiceLiveAgent
      class: MetadataFilenameParser
      extension: EmbeddedServiceLiveAgent
escalationRules:
    - type: EscalationRules
      class: MetadataFilenameParser
      extension: escalationRules
experiences:
    - type: ExperienceBundle
      class: BundleParser
externalServiceRegistrations:
    - type: ExternalServiceRegistration
      class: MetadataFilenameParser
      extension: externalServiceRegistration
featureParameters:
    - type: FeatureParameterBoolean
      class: MetadataFilenameParser
      extension: featureParameterBoolean
    - type: FeatureParameterDate
      class: MetadataFilenameParser
      extension: featureParameterDate
    - type: FeatureParameterInteger
      class: MetadataFilenameParser
      extension: featureParameterInteger
flexipages:
    - type: FlexiPage
      class: MetadataFilenameParser
      extension: flexipage
flows:
    - type: Flow
      class: MetadataFilenameParser
      extension: flow
flowCategories:
    - type: FlowCategory
      class: MetadataFilenameParser
      extension: flowCategory
flowDefinitions:
    - type: FlowDefinition
      class: MetadataFilenameParser
      extension: flowDefinition
globalPicklist:
    - type: GlobalPicklist
      class: MetadataFilenameParser
      extension: globalPicklist
globalValueSets:
    - type: GlobalValueSet
      class: MetadataFilenameParser
      extension: globalValueSet
globalValueSetTranslations:
    - type: GlobalValueSetTranslation
      class: MetadataFilenameParser
      extension: globalValueSetTranslation
groups:
    - type: Group
      class: MetadataFilenameParser
      extension: group
homePageComponents:
    - type: HomePageComponent
      class: MetadataFilenameParser
      extension: homePageComponent
homePageLayouts:
    - type: HomePageLayout
      class: MetadataFilenameParser
      extension: homePageLayout
labels:
    - type: CustomLabel
      class: CustomLabelsParser
      extension: labels
      options:
            item_xpath: './sf:labels'
    - type: CustomLabels
      class: MetadataFilenameParser
      extension: labels
layouts:
    - type: Layout
      class: MetadataFilenameParser
      extension: layout
letterhead:
    - type: Letterhead
      class: MetadataFilenameParser
      extension: letter
lightningBolts:
    - type: LightningBolt
      class: MetadataFilenameParser
      extension: lightningBolt
lightningExperienceThemes:
    - type: LightningExperienceTheme
      class: MetadataFilenameParser
      extension: lightningExperienceTheme
liveChatButtons:
    - type: LiveChatButton
      class: MetadataFilenameParser
      extension: liveChatButton
liveChatDeployments:
    - type: LiveChatDeployment
      class: MetadataFilenameParser
      extension: liveChatDeployment

lwc:
    - type: LightningComponentBundle
      class: LWCBundleParser
matchingRules:
    - type: MatchingRule
      class: MetadataXmlElementParser
      extension: matchingRule
      options:
            item_xpath: './sf:matchingRules'
messageChannels:
    - type: LightningMessageChannel
      class: MetadataFilenameParser
      extension: messageChannel
mlDomains:
    - type: MlDomain
      class: MetadataFilenameParser
      extension: mlDomain
MobileApplicationDetails:
    - type: MobileApplicationDetail
      class: MetadataFilenameParser
      extension: MobileApplicationDetail
mutingpermissionsets:
    - type: MutingPermissionSet
      class: MetadataFilenameParser
      extension: mutingpermissionset
navigationMenus:
    - type: NavigationMenu
      class: MetadataFilenameParser
      extension: navigationMenu
namedCredentials:
    - type: NamedCredential
      class: MetadataFilenameParser
      extension: namedCredential
networkBranding:
    - type: NetworkBranding
      class: MetadataFilenameParser
      extension: networkBranding            
networks:
    - type: Network
      class: MetadataFilenameParser
      extension: network
notificationTypeConfig:
    - type: NotificationTypeConfig
      class: MetadataFilenameParser
      extension: config
notificationtypes:
    - type: CustomNotificationType
      class: MetadataFilenameParser
      extension: notiftype
oauthcustomscopes:
    - type: OauthCustomScope
      class: MetadataFilenameParser
      extension: oauthcustomscope    
objects:
    - type: CustomObject
      class: CustomObjectParser
      extension: object
    - type: BusinessProcess
      class: BusinessProcessParser
      extension: object
      options:
            item_xpath: './sf:businessProcesses'
    - type: CompactLayout
      class: MetadataXmlElementParser
      extension: object
      options:
            item_xpath: './sf:compactLayouts'
    - type: CustomField
      class: MetadataXmlElementParser
      extension: object
      options:
            item_xpath: './sf:fields'
    - type: FieldSet
      class: MetadataXmlElementParser
      extension: object
      options:
            item_xpath: './sf:fieldSets'
    - type: Index
      class: MetadataXmlElementParser
      extension: object
      options:
            item_xpath: './sf:indexes'
    - type: ListView
      class: MetadataXmlElementParser
      extension: object
      options:
            item_xpath: './sf:listViews'
    - type: NamedFilter
      class: MetadataXmlElementParser
      extension: object
      options:
            item_xpath: './sf:namedFilters'
    - type: RecordType
      class: RecordTypeParser
      extension: object
      options:
            item_xpath: './sf:recordTypes'
    - type: SharingReason
      class: MetadataXmlElementParser
      extension: object
      options:
            item_xpath: './sf:sharingReasons'
    - type: ValidationRule
      class: MetadataXmlElementParser
      extension: object
      options:
            item_xpath: './sf:validationRules'
    - type: WebLink
      class: MetadataXmlElementParser
      extension: object
      options:
            item_xpath: './sf:webLinks'
objectTranslations:
    - type: CustomObjectTranslation
      class: MetadataFilenameParser
      extension: objectTranslation
pages:
    - type: ApexPage
      class: MetadataFilenameParser
      extension: page
pathAssistants:
    - type: PathAssistant
      class: MetadataFilenameParser
      extension: pathAssistant
paymentGatewayProviders:
    - type: PaymentGatewayProvider
      class: MetadataFilenameParser
      extension: paymentGatewayProvider
permissionsets:
    - type: PermissionSet
      class: MetadataFilenameParser
      extension: permissionset
permissionsetgroups:
    - type: PermissionSetGroup
      class: MetadataFilenameParser
      extension: permissionsetgroup
platformEventChannels:
    - type: PlatformEventChannel
      class: MetadataFilenameParser
      extension: platformEventChannel
platformEventChannelMembers:
    - type: PlatformEventChannelMember
      class: MetadataFilenameParser
      extension: platformEventChannelMember
postTemplates:
    - type: PostTemplate
      class: MetadataFilenameParser
      extension: postTemplate
profiles:
    - type: Profile
      class: MetadataFilenameParser
      extension: profile
profilePasswordPolicies:
    - type: ProfilePasswordPolicy
      class: MetadataFilenameParser
      extension: profilePasswordPolicy
profileSessionSettings:
    - type: ProfileSessionSetting
      class: MetadataFilenameParser
      extension: profileSessionSetting
prompts:
    - type: Prompt
      class: MetadataFilenameParser
      extension: prompt
queues:
    - type: Queue
      class: MetadataFilenameParser
      extension: queue
quickActions:
    - type: QuickAction
      class: MetadataFilenameParser
      extension: quickAction
queueRoutingConfigs:
    - type: QueueRoutingConfig
      class: MetadataFilenameParser
      extension: queueRoutingConfig
recommendationStrategies:
    - type: RecommendationStrategy
      class: MetadataFilenameParser
      extension: recommendationStrategy
recordActionDeployments:
    - type: RecordActionDeployment
      class: MetadataFilenameParser
      extension: deployment
remoteSiteSettings:
    - type: RemoteSiteSetting
      class: MetadataFilenameParser
      extension: remoteSite
reportTypes:
    - type: ReportType
      class: MetadataFilenameParser
      extension: reportType
reports:
    - type: Report
      class: MetadataFolderParser
roles:
    - type: Role 
      class: MetadataFilenameParser
      extension: role
samlssoconfigs:
    - type: SamlSsoConfig
      class: MetadataFilenameParser
      extension: samlssoconfig
settings:
    - type: Settings
      class: MetadataFilenameParser
      extension: settings
scontrols:
    - type: Scontrol
      class: MetadataFilenameParser
      extension: scf
sharingRules:
    - type: SharingCriteriaRule
      class: MetadataXmlElementParser
      extension: sharingRules
      options:
            item_xpath: './sf:sharingCriteriaRules'
    - type: SharingGuestRule
      class: MetadataXmlElementParser
      extension: sharingRules
      options:
            item_xpath: './sf:sharingGuestRules'
    - type: SharingOwnerRule
      class: MetadataXmlElementParser
      extension: sharingRules
      options:
            item_xpath: './sf:sharingOwnerRules'
    - type: SharingTerritoryRule
      class: MetadataXmlElementParser
      extension: sharingRules
      options:
            item_xpath: './sf:sharingTerritoryRules'
sharingSets:
    - type: SharingSet
      class: MetadataFilenameParser
      extension: sharingSet  
siteDotComSites:
    - type: SiteDotCom 
      class: MetadataFilenameParser
      extension: site 
sites:
    - type: CustomSite 
      class: MetadataFilenameParser
      extension: site
skills:
    - type: Skill
      class: MetadataFilenameParser
      extension: skill
standardValueSets:
    - type: StandardValueSet
      class: MetadataFilenameParser
      extension: standardValueSet
standardValueSetTranslations:
    - type: StandardValueSetTranslation
      class: MetadataFilenameParser
      extension: standardValueSetTranslation
staticresources:
    - type: StaticResource
      class: MetadataFilenameParser
      extension: resource
synonymDictionaries:
    - type: SynonymDictionary
      class: MetadataFilenameParser
      extension: synonymDictionary
tabs:
    - type: CustomTab
      class: MetadataFilenameParser
      extension: tab
testSuites:
    - type: ApexTestSuite
      class: MetadataFilenameParser
      extension: testSuite
timeSheetTemplates:
    - type: TimeSheetTemplate
      class: MetadataFilenameParser
      extension: timeSheetTemplate
topicsForObjects:
    - type: TopicsForObjects
      class: MetadataFilenameParser
      extension: topicsForObjects
translations:
    - type: Translations
      class: MetadataFilenameParser
      extension: translation
triggers:
    - type: ApexTrigger
      class: MetadataFilenameParser
      extension: trigger
wave:
    - type: WaveApplication
      class: MetadataFilenameParser
      extension: wapp
    - type: WaveDashboard
      class: MetadataFilenameParser
      extension: wdash
    - type: WaveDataset
      class: MetadataFilenameParser
      extension: wds
    - type: WaveDataflow
      class: MetadataFilenameParser
      extension: wdf
    - type: WaveLens
      class: MetadataFilenameParser
      extension: wlens
    - type: WaveRecipe
      class: MetadataFilenameParser
      extension: wdpr
    - type: WaveXmd
      class: MetadataFilenameParser
      extension: xmd
waveTemplates:
    - type: WaveTemplateBundle
      class: BundleParser
weblinks:
    - type: CustomPageWebLink
      class: MetadataFilenameParser
      extension: weblink
workflows:
    - type: WorkflowAlert
      class: MetadataXmlElementParser
      extension: workflow
      options:
            item_xpath: './sf:alerts'
    - type: WorkflowFieldUpdate
      class: MetadataXmlElementParser
      extension: workflow
      options:
            item_xpath: './sf:fieldUpdates'
    - type: WorkflowOutboundMessage
      class: MetadataXmlElementParser
      extension: workflow
      options:
            item_xpath: './sf:outboundMessages'    
    - type: WorkflowRule
      class: MetadataXmlElementParser
      extension: workflow
      options:
            item_xpath: './sf:rules'
    - type: WorkflowTask
      class: MetadataXmlElementParser
      extension: workflow
      options:
            item_xpath: './sf:tasks'
