name: Build Homebrew formula

on:
    release:
        types:
            - created
    workflow_dispatch:

jobs:
    build:
        name: Build Homebrew formula
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@main
            - name: Set up Python 3.9
              uses: actions/setup-python@v2
              with:
                  python-version: 3.9
            - name: Build formula
              run: |
                  python -m pip install pip-tools
                  utility/build-homebrew.sh cumulusci.rb
            - name: Test formula
              run: |
                  brew audit cumulusci.rb
                  brew install cumulusci.rb
                  brew test cumulusci.rb
            - name: Create branch in homebrew-sfdo repository
              run: |
                  VERSION=$(python setup.py --version)
                  BRANCH="cci-$VERSION"
                  git clone https://HOMEBREW_GITHUB_USER:HOMEBREW_GITHUB_TOKEN@github.com/SFDO-Tooling/homebrew-sfdo.git
                  cd homebrew-sfdo
                  git checkout -b $BRANCH
                  cp ../cumulusci.rb ./
                  git add cumulusci.rb
                  git commit -m "Bump cumulusci to version $VERSION"
                  git push origin $BRANCH
