name: Release Test

on:
  push:
    branches:
      - feature/**
      - main

env:
  CUMULUSCI_ORG_scratch: '{"config_file": "orgs/dev.json", "scratch": true}'
  CUMULUSCI_ORG_packaging: ${{ secrets.CUMULUSCI_ORG_packaging }}
  CUMULUSCI_SERVICE_github: ${{ secrets.CUMULUSCI_SERVICE_github }}
  SFDX_CLIENT_ID: ${{ secrets.SFDX_CLIENT_ID }}
  SFDX_HUB_KEY: ${{ secrets.SFDX_HUB_KEY }}
  SFDX_HUB_KEY_BASE64: ${{ secrets.SFDX_HUB_KEY_BASE64 }}
  SFDX_HUB_USERNAME: ${{ secrets.SFDX_HUB_USERNAME }}

jobs:
  test_release:
    name: "Test Release Flows"
    runs-on: ubuntu-latest
    env:
      CUMULUSCI_KEYCHAIN_CLASS: cumulusci.core.keychain.EnvironmentProjectKeychain
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: pip cache
        uses: actions/cache@v1
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements/*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Python dependencies
        run: |
          python -m pip install -U pip pip-tools
          make dev-install
      - name: Install sfdx
        run: |
          mkdir sfdx
          wget -qO- https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz | tar xJ -C sfdx --strip-components 1
          echo $(realpath sfdx/bin) >> $GITHUB_PATH
      - name: Authenticate Dev Hub
        run: |
          sfdx plugins --core
          echo $SFDX_HUB_KEY_BASE64 | base64 --decode > sfdx.key
          sfdx auth:jwt:grant --clientid $SFDX_CLIENT_ID --jwtkeyfile sfdx.key --username $SFDX_HUB_USERNAME --setdefaultdevhubusername -a hub
      - name: Check out CumulusCI-Test
        run: |
          git clone https://github.com/SFDO-Tooling/CumulusCI-Test
      - name: Run ci_feature flow
        run: |
          cd CumulusCI-Test
          coverage run --append --rcfile=../pyproject.toml --source=../cumulusci $(which cci) flow run ci_feature --org scratch --delete-org --debug
      - name: Run ci_beta flow
        run: |
          cd CumulusCI-Test
          coverage run --append --rcfile=../pyproject.toml --source=../cumulusci $(which cci) flow run ci_beta --org scratch --delete-org --debug
      - name: Run ci_master flow
        run: |
          cd CumulusCI-Test
          coverage run --append --rcfile=../pyproject.toml --source=../cumulusci $(which cci) flow run ci_master --org scratch --delete-org --debug
      - name: Run release_beta flow
        run: |
          export SFDX_HUB_KEY="$(echo $SFDX_HUB_KEY_BASE64 | base64 --decode)"
          cd CumulusCI-Test
          coverage run --append --rcfile=../pyproject.toml --source=../cumulusci $(which cci) flow run release_beta --org packaging --debug
